### ISSUE TITLE
Add a built-in cargo feature?

### ISSUE THREAD

**Issue by Keats** [Keats/tera#375]
Right now the default Tera will pull quite a few dependencies:

```toml
globwalk = "0.5"
serde = "1.0"
serde_json = "1.0"
pest = "2"
pest_derive = "2"
# used in slugify filter
slug = "0.1"
# used in striptags filters
regex = "1.0"
# used for static regex
lazy_static = "1.0"
# used in urlencode filter
url = "1"
# used in filesizeformat filter
humansize = "1"
# used in date format filter
chrono = "0.4"
# used in truncate filter
unic-segment = "0.8"
```

It might be reasonable to have a `builtins` feature on by default that contains all the non-essential crates so people not needing those will only have globwalk/serde/pest as direct dependencies.
