### ISSUE TITLE
preserve_order not longer work?

### ISSUE THREAD

**Issue by mamcx** [Keats/tera#735]
Somehow since I use tera and upgrade a long the way `preserve_order` stop working for me:

```toml
serde = { version = "1.0.136", features = ["derive"] }
serde_json = { version ="*", features = [ "preserve_order" ]}
tera = { version = "1.16.0", features = ["preserve_order"] }
```

```rust
pub struct Schema {
    pub fields: BTreeMap<Fields, Column>,
}

Schema::new(
            &[
                Column::link(Fields::warehouse_code),
                Column::text(Fields::name),
            ],
        )
```

When I output this I get:

```json
{ "name": { "field": "name", "title": "Name", "kind": "String", "sort": "No" }, "warehouse_code": { "field": "warehouse_code", "title": "Code", "kind": "Link", "sort": "Asc" } } 
```
