### ISSUE TITLE
Add a way to partially render a template (ignore missing variables in context)

### ISSUE THREAD

**Issue by minev-dev** [Keats/tera#962]
## Problem

There is no way to partially render a template with the only variables available in a context and ignore the template variables that are not presented in the context.

Currently the `Processor::render` returns an error if at least one variable is failed to render
https://github.com/Keats/tera/blob/ae13d7ce39d732aae3f68435ed52c60732fe0ee0/src/renderer/processor.rs#L1058-L1062

## Context

We have a multi-step rendering where not all the variables are available at the same time. There is a config file which should support system env variables injection (first step) and then cross-services variables injection in runtime (second step).

Here is a draft PR with the implementation and failing unit test https://github.com/opencloudtool/opencloudtool/pull/283/commits/20ae6de0b2fb1b25c666c28591b44aa113330b4f

### Initial template

```toml
[project]
name = "{{ env.PROJECT_NAME }}"
description = "{{ runtime.GOOD_DESCRIPTION }}"
```

#### Context

```
{
  "env": {
    "PROJECT_NAME": "Project Name"
  }
}
```

#### Rendered template

```toml
[project]
name = "Project Name"
description = "{{ runtime.GOOD_DESCRIPTION }}"
```

#### Context

```
{
  "runtime": {
    "GOOD_DESCRIPTION": "Good Description"
  }
}
```

#### Rendered template

```toml
[project]
name = "Project Name"
description = "Good Description"
```
